### Schema


CREATE DATABASE IF NOT EXISTS burgers_db;
USE burgers_db;
DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
  id INT NOT NULL AUTO_INCREMENT,
  burger VARCHAR(45) NOT NULL,
  eaten BOOL DEFAULT FALSE,
  PRIMARY KEY (id)
  )
ENGINE = InnoDB